package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private Integer accountId;
     private Calendar calendar;
     private String firstName;
     private String lastName;
     private String password;
     private String email;
     private String isAdmin;
     private Set wikicomments = new HashSet(0);
     private Set projectaccountmappings = new HashSet(0);
     private Set workitemsForAsigneeId = new HashSet(0);
     private Set workitemsForAuthorId = new HashSet(0);
     private Set wikipages = new HashSet(0);
     private Set workitemcomments = new HashSet(0);

    public Account() {
    }

	
    public Account(Calendar calendar, String firstName, String lastName, String password, String email, String isAdmin) {
        this.calendar = calendar;
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.isAdmin = isAdmin;
    }
    public Account(Calendar calendar, String firstName, String lastName, String password, String email, String isAdmin, Set wikicomments, Set projectaccountmappings, Set workitemsForAsigneeId, Set workitemsForAuthorId, Set wikipages, Set workitemcomments) {
       this.calendar = calendar;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
       this.email = email;
       this.isAdmin = isAdmin;
       this.wikicomments = wikicomments;
       this.projectaccountmappings = projectaccountmappings;
       this.workitemsForAsigneeId = workitemsForAsigneeId;
       this.workitemsForAuthorId = workitemsForAuthorId;
       this.wikipages = wikipages;
       this.workitemcomments = workitemcomments;
    }
   
    public Integer getAccountId() {
        return this.accountId;
    }
    
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }
    public Calendar getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Calendar calendar) {
        this.calendar = calendar;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(String isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getWikicomments() {
        return this.wikicomments;
    }
    
    public void setWikicomments(Set wikicomments) {
        this.wikicomments = wikicomments;
    }
    public Set getProjectaccountmappings() {
        return this.projectaccountmappings;
    }
    
    public void setProjectaccountmappings(Set projectaccountmappings) {
        this.projectaccountmappings = projectaccountmappings;
    }
    public Set getWorkitemsForAsigneeId() {
        return this.workitemsForAsigneeId;
    }
    
    public void setWorkitemsForAsigneeId(Set workitemsForAsigneeId) {
        this.workitemsForAsigneeId = workitemsForAsigneeId;
    }
    public Set getWorkitemsForAuthorId() {
        return this.workitemsForAuthorId;
    }
    
    public void setWorkitemsForAuthorId(Set workitemsForAuthorId) {
        this.workitemsForAuthorId = workitemsForAuthorId;
    }
    public Set getWikipages() {
        return this.wikipages;
    }
    
    public void setWikipages(Set wikipages) {
        this.wikipages = wikipages;
    }
    public Set getWorkitemcomments() {
        return this.workitemcomments;
    }
    
    public void setWorkitemcomments(Set workitemcomments) {
        this.workitemcomments = workitemcomments;
    }




}


