package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1



/**
 * Dependency generated by hbm2java
 */
public class Dependency  implements java.io.Serializable {


     private Integer dependencyId;
     private Workitem workitemByWorkItemId1;
     private Workitem workitemByWorkItemId2;
     private Dependencytype dependencytype;

    public Dependency() {
    }

    public Dependency(Workitem workitemByWorkItemId1, Workitem workitemByWorkItemId2, Dependencytype dependencytype) {
       this.workitemByWorkItemId1 = workitemByWorkItemId1;
       this.workitemByWorkItemId2 = workitemByWorkItemId2;
       this.dependencytype = dependencytype;
    }
   
    public Integer getDependencyId() {
        return this.dependencyId;
    }
    
    public void setDependencyId(Integer dependencyId) {
        this.dependencyId = dependencyId;
    }
    public Workitem getWorkitemByWorkItemId1() {
        return this.workitemByWorkItemId1;
    }
    
    public void setWorkitemByWorkItemId1(Workitem workitemByWorkItemId1) {
        this.workitemByWorkItemId1 = workitemByWorkItemId1;
    }
    public Workitem getWorkitemByWorkItemId2() {
        return this.workitemByWorkItemId2;
    }
    
    public void setWorkitemByWorkItemId2(Workitem workitemByWorkItemId2) {
        this.workitemByWorkItemId2 = workitemByWorkItemId2;
    }
    public Dependencytype getDependencytype() {
        return this.dependencytype;
    }
    
    public void setDependencytype(Dependencytype dependencytype) {
        this.dependencytype = dependencytype;
    }




}


