package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer eventId;
     private Calendar calendar;
     private Date dateTime;
     private String name;
     private String location;
     private String description;

    public Event() {
    }

	
    public Event(Calendar calendar, Date dateTime, String name) {
        this.calendar = calendar;
        this.dateTime = dateTime;
        this.name = name;
    }
    public Event(Calendar calendar, Date dateTime, String name, String location, String description) {
       this.calendar = calendar;
       this.dateTime = dateTime;
       this.name = name;
       this.location = location;
       this.description = description;
    }
   
    public Integer getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }
    public Calendar getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Calendar calendar) {
        this.calendar = calendar;
    }
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


