package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Projectclass generated by hbm2java
 */
public class Projectclass  implements java.io.Serializable {


     private Integer classId;
     private String name;
     private String description;
     private Set projects = new HashSet(0);

    public Projectclass() {
    }

	
    public Projectclass(String name) {
        this.name = name;
    }
    public Projectclass(String name, String description, Set projects) {
       this.name = name;
       this.description = description;
       this.projects = projects;
    }
   
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }




}


