package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer roleId;
     private String name;
     private String description;
     private Set projectaccountmappings = new HashSet(0);

    public Role() {
    }

	
    public Role(String name) {
        this.name = name;
    }
    public Role(String name, String description, Set projectaccountmappings) {
       this.name = name;
       this.description = description;
       this.projectaccountmappings = projectaccountmappings;
    }
   
    public Integer getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getProjectaccountmappings() {
        return this.projectaccountmappings;
    }
    
    public void setProjectaccountmappings(Set projectaccountmappings) {
        this.projectaccountmappings = projectaccountmappings;
    }




}


