package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Workitemcomment generated by hbm2java
 */
public class Workitemcomment  implements java.io.Serializable {


     private int workItemCommentId;
     private Workitem workitem;
     private Account account;
     private Date lastModifyDate;
     private String content;

    public Workitemcomment() {
    }

    public Workitemcomment(int workItemCommentId, Workitem workitem, Account account, Date lastModifyDate, String content) {
       this.workItemCommentId = workItemCommentId;
       this.workitem = workitem;
       this.account = account;
       this.lastModifyDate = lastModifyDate;
       this.content = content;
    }
   
    public int getWorkItemCommentId() {
        return this.workItemCommentId;
    }
    
    public void setWorkItemCommentId(int workItemCommentId) {
        this.workItemCommentId = workItemCommentId;
    }
    public Workitem getWorkitem() {
        return this.workitem;
    }
    
    public void setWorkitem(Workitem workitem) {
        this.workitem = workitem;
    }
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }
    public Date getLastModifyDate() {
        return this.lastModifyDate;
    }
    
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }




}


