// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.Attachment;
import org.hcmus.tis.model.AttachmentDataOnDemand;
import org.hcmus.tis.model.AttachmentIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AttachmentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AttachmentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AttachmentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AttachmentIntegrationTest: @Transactional;
    
    @Autowired
    private AttachmentDataOnDemand AttachmentIntegrationTest.dod;
    
    @Test
    public void AttachmentIntegrationTest.testCountAttachments() {
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", dod.getRandomAttachment());
        long count = Attachment.countAttachments();
        Assert.assertTrue("Counter for 'Attachment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AttachmentIntegrationTest.testFindAttachment() {
        Attachment obj = dod.getRandomAttachment();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to provide an identifier", id);
        obj = Attachment.findAttachment(id);
        Assert.assertNotNull("Find method for 'Attachment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Attachment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AttachmentIntegrationTest.testFindAllAttachments() {
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", dod.getRandomAttachment());
        long count = Attachment.countAttachments();
        Assert.assertTrue("Too expensive to perform a find all test for 'Attachment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Attachment> result = Attachment.findAllAttachments();
        Assert.assertNotNull("Find all method for 'Attachment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Attachment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AttachmentIntegrationTest.testFindAttachmentEntries() {
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", dod.getRandomAttachment());
        long count = Attachment.countAttachments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Attachment> result = Attachment.findAttachmentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Attachment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Attachment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AttachmentIntegrationTest.testFlush() {
        Attachment obj = dod.getRandomAttachment();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to provide an identifier", id);
        obj = Attachment.findAttachment(id);
        Assert.assertNotNull("Find method for 'Attachment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAttachment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Attachment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttachmentIntegrationTest.testMergeUpdate() {
        Attachment obj = dod.getRandomAttachment();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to provide an identifier", id);
        obj = Attachment.findAttachment(id);
        boolean modified =  dod.modifyAttachment(obj);
        Integer currentVersion = obj.getVersion();
        Attachment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Attachment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AttachmentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", dod.getRandomAttachment());
        Attachment obj = dod.getNewTransientAttachment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Attachment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Attachment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Attachment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AttachmentIntegrationTest.testRemove() {
        Attachment obj = dod.getRandomAttachment();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Attachment' failed to provide an identifier", id);
        obj = Attachment.findAttachment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Attachment' with identifier '" + id + "'", Attachment.findAttachment(id));
    }
    
}
