// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Iteration;
import org.hcmus.tis.model.IterationDataOnDemand;
import org.hcmus.tis.model.WorkItemContainer;
import org.springframework.stereotype.Component;

privileged aspect IterationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IterationDataOnDemand: @Component;
    
    private Random IterationDataOnDemand.rnd = new SecureRandom();
    
    private List<Iteration> IterationDataOnDemand.data;
    
    public Iteration IterationDataOnDemand.getNewTransientIteration(int index) {
        Iteration obj = new Iteration();
        setName(obj, index);
        setParentContainer(obj, index);
        return obj;
    }
    
    public void IterationDataOnDemand.setName(Iteration obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void IterationDataOnDemand.setParentContainer(Iteration obj, int index) {
        WorkItemContainer parentContainer = null;
        obj.setParentContainer(parentContainer);
    }
    
    public Iteration IterationDataOnDemand.getSpecificIteration(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Iteration obj = data.get(index);
        Long id = obj.getId();
        return Iteration.findIteration(id);
    }
    
    public Iteration IterationDataOnDemand.getRandomIteration() {
        init();
        Iteration obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Iteration.findIteration(id);
    }
    
    public boolean IterationDataOnDemand.modifyIteration(Iteration obj) {
        return false;
    }
    
    public void IterationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Iteration.findIterationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Iteration' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Iteration>();
        for (int i = 0; i < 10; i++) {
            Iteration obj = getNewTransientIteration(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
