// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.MemberInformationIntegrationTest;
import org.hcmus.tis.repository.MemberInformationRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MemberInformationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MemberInformationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MemberInformationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MemberInformationIntegrationTest: @Transactional;
    
    @Autowired
    MemberInformationRepository MemberInformationIntegrationTest.memberInformationRepository;
    
    @Test
    public void MemberInformationIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = memberInformationRepository.count();
        Assert.assertTrue("Counter for 'MemberInformation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFind() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = memberInformationRepository.findOne(id);
        Assert.assertNotNull("Find method for 'MemberInformation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MemberInformation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = memberInformationRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'MemberInformation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MemberInformation> result = memberInformationRepository.findAll();
        Assert.assertNotNull("Find all method for 'MemberInformation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MemberInformation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = memberInformationRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MemberInformation> result = memberInformationRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'MemberInformation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MemberInformation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFlush() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = memberInformationRepository.findOne(id);
        Assert.assertNotNull("Find method for 'MemberInformation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMemberInformation(obj);
        Integer currentVersion = obj.getVersion();
        memberInformationRepository.flush();
        Assert.assertTrue("Version for 'MemberInformation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testSaveUpdate() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = memberInformationRepository.findOne(id);
        boolean modified =  dod.modifyMemberInformation(obj);
        Integer currentVersion = obj.getVersion();
        MemberInformation merged = memberInformationRepository.save(obj);
        memberInformationRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MemberInformation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        MemberInformation obj = dod.getNewTransientMemberInformation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MemberInformation' identifier to be null", obj.getId());
        memberInformationRepository.save(obj);
        memberInformationRepository.flush();
        Assert.assertNotNull("Expected 'MemberInformation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testDelete() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = memberInformationRepository.findOne(id);
        memberInformationRepository.delete(obj);
        memberInformationRepository.flush();
        Assert.assertNull("Failed to remove 'MemberInformation' with identifier '" + id + "'", memberInformationRepository.findOne(id));
    }
    
}
