// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.MemberInformation;
import org.hcmus.tis.model.MemberInformationDataOnDemand;
import org.hcmus.tis.model.MemberInformationIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MemberInformationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MemberInformationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MemberInformationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MemberInformationIntegrationTest: @Transactional;
    
    @Autowired
    private MemberInformationDataOnDemand MemberInformationIntegrationTest.dod;
    
    @Test
    public void MemberInformationIntegrationTest.testCountMemberInformations() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = MemberInformation.countMemberInformations();
        Assert.assertTrue("Counter for 'MemberInformation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFindMemberInformation() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = MemberInformation.findMemberInformation(id);
        Assert.assertNotNull("Find method for 'MemberInformation' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MemberInformation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFindAllMemberInformations() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = MemberInformation.countMemberInformations();
        Assert.assertTrue("Too expensive to perform a find all test for 'MemberInformation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MemberInformation> result = MemberInformation.findAllMemberInformations();
        Assert.assertNotNull("Find all method for 'MemberInformation' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MemberInformation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFindMemberInformationEntries() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        long count = MemberInformation.countMemberInformations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MemberInformation> result = MemberInformation.findMemberInformationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MemberInformation' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MemberInformation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testFlush() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = MemberInformation.findMemberInformation(id);
        Assert.assertNotNull("Find method for 'MemberInformation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMemberInformation(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MemberInformation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testMergeUpdate() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = MemberInformation.findMemberInformation(id);
        boolean modified =  dod.modifyMemberInformation(obj);
        Integer currentVersion = obj.getVersion();
        MemberInformation merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MemberInformation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MemberInformationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", dod.getRandomMemberInformation());
        MemberInformation obj = dod.getNewTransientMemberInformation(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MemberInformation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MemberInformation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MemberInformationIntegrationTest.testRemove() {
        MemberInformation obj = dod.getRandomMemberInformation();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MemberInformation' failed to provide an identifier", id);
        obj = MemberInformation.findMemberInformation(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MemberInformation' with identifier '" + id + "'", MemberInformation.findMemberInformation(id));
    }
    
}
