// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import org.hcmus.tis.model.PriorityDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PriorityDataOnDemand_Roo_Configurable {
    
    declare @type: PriorityDataOnDemand: @Configurable;
    
}
