// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.StudyClass;
import org.hcmus.tis.model.StudyClassDataOnDemand;
import org.hcmus.tis.model.StudyClassIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudyClassIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StudyClassIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StudyClassIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StudyClassIntegrationTest: @Transactional;
    
    @Autowired
    private StudyClassDataOnDemand StudyClassIntegrationTest.dod;
    
    @Test
    public void StudyClassIntegrationTest.testCountStudyClasses() {
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", dod.getRandomStudyClass());
        long count = StudyClass.countStudyClasses();
        Assert.assertTrue("Counter for 'StudyClass' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StudyClassIntegrationTest.testFindStudyClass() {
        StudyClass obj = dod.getRandomStudyClass();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to provide an identifier", id);
        obj = StudyClass.findStudyClass(id);
        Assert.assertNotNull("Find method for 'StudyClass' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'StudyClass' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StudyClassIntegrationTest.testFindAllStudyClasses() {
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", dod.getRandomStudyClass());
        long count = StudyClass.countStudyClasses();
        Assert.assertTrue("Too expensive to perform a find all test for 'StudyClass', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<StudyClass> result = StudyClass.findAllStudyClasses();
        Assert.assertNotNull("Find all method for 'StudyClass' illegally returned null", result);
        Assert.assertTrue("Find all method for 'StudyClass' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StudyClassIntegrationTest.testFindStudyClassEntries() {
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", dod.getRandomStudyClass());
        long count = StudyClass.countStudyClasses();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<StudyClass> result = StudyClass.findStudyClassEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'StudyClass' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'StudyClass' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StudyClassIntegrationTest.testFlush() {
        StudyClass obj = dod.getRandomStudyClass();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to provide an identifier", id);
        obj = StudyClass.findStudyClass(id);
        Assert.assertNotNull("Find method for 'StudyClass' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStudyClass(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'StudyClass' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudyClassIntegrationTest.testMergeUpdate() {
        StudyClass obj = dod.getRandomStudyClass();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to provide an identifier", id);
        obj = StudyClass.findStudyClass(id);
        boolean modified =  dod.modifyStudyClass(obj);
        Integer currentVersion = obj.getVersion();
        StudyClass merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'StudyClass' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StudyClassIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", dod.getRandomStudyClass());
        StudyClass obj = dod.getNewTransientStudyClass(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'StudyClass' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'StudyClass' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StudyClassIntegrationTest.testRemove() {
        StudyClass obj = dod.getRandomStudyClass();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'StudyClass' failed to provide an identifier", id);
        obj = StudyClass.findStudyClass(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'StudyClass' with identifier '" + id + "'", StudyClass.findStudyClass(id));
    }
    
}
