// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.WorkItemType;
import org.hcmus.tis.model.WorkItemTypeDataOnDemand;
import org.hcmus.tis.model.WorkItemTypeIntegrationTest;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkItemTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkItemTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkItemTypeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkItemTypeIntegrationTest: @Transactional;
    
    @Autowired
    private WorkItemTypeDataOnDemand WorkItemTypeIntegrationTest.dod;
    
    @Test
    public void WorkItemTypeIntegrationTest.testCountWorkItemTypes() {
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", dod.getRandomWorkItemType());
        long count = WorkItemType.countWorkItemTypes();
        Assert.assertTrue("Counter for 'WorkItemType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testFindWorkItemType() {
        WorkItemType obj = dod.getRandomWorkItemType();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to provide an identifier", id);
        obj = WorkItemType.findWorkItemType(id);
        Assert.assertNotNull("Find method for 'WorkItemType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WorkItemType' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testFindAllWorkItemTypes() {
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", dod.getRandomWorkItemType());
        long count = WorkItemType.countWorkItemTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'WorkItemType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WorkItemType> result = WorkItemType.findAllWorkItemTypes();
        Assert.assertNotNull("Find all method for 'WorkItemType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WorkItemType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testFindWorkItemTypeEntries() {
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", dod.getRandomWorkItemType());
        long count = WorkItemType.countWorkItemTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WorkItemType> result = WorkItemType.findWorkItemTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'WorkItemType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WorkItemType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testFlush() {
        WorkItemType obj = dod.getRandomWorkItemType();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to provide an identifier", id);
        obj = WorkItemType.findWorkItemType(id);
        Assert.assertNotNull("Find method for 'WorkItemType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkItemType(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'WorkItemType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testMergeUpdate() {
        WorkItemType obj = dod.getRandomWorkItemType();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to provide an identifier", id);
        obj = WorkItemType.findWorkItemType(id);
        boolean modified =  dod.modifyWorkItemType(obj);
        Integer currentVersion = obj.getVersion();
        WorkItemType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WorkItemType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", dod.getRandomWorkItemType());
        WorkItemType obj = dod.getNewTransientWorkItemType(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WorkItemType' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'WorkItemType' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkItemTypeIntegrationTest.testRemove() {
        WorkItemType obj = dod.getRandomWorkItemType();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItemType' failed to provide an identifier", id);
        obj = WorkItemType.findWorkItemType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'WorkItemType' with identifier '" + id + "'", WorkItemType.findWorkItemType(id));
    }
    
}
