// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Account;
import org.hcmus.tis.model.AccountDataOnDemand;
import org.hcmus.tis.model.MemberInformation;
import org.hcmus.tis.model.MemberInformationDataOnDemand;
import org.hcmus.tis.model.Priority;
import org.hcmus.tis.model.PriorityDataOnDemand;
import org.hcmus.tis.model.WorkItem;
import org.hcmus.tis.model.WorkItemDataOnDemand;
import org.hcmus.tis.model.WorkItemStatus;
import org.hcmus.tis.model.WorkItemStatusDataOnDemand;
import org.hcmus.tis.model.WorkItemType;
import org.hcmus.tis.model.WorkItemTypeDataOnDemand;
import org.hcmus.tis.repository.WorkItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect WorkItemDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkItemDataOnDemand: @Component;
    
    private Random WorkItemDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkItem> WorkItemDataOnDemand.data;
    
    @Autowired
    private MemberInformationDataOnDemand WorkItemDataOnDemand.memberInformationDataOnDemand;
    
    @Autowired
    private PriorityDataOnDemand WorkItemDataOnDemand.priorityDataOnDemand;
    
    @Autowired
    private WorkItemStatusDataOnDemand WorkItemDataOnDemand.workItemStatusDataOnDemand;
    
    @Autowired
    private AccountDataOnDemand WorkItemDataOnDemand.accountDataOnDemand;
    
    @Autowired
    private WorkItemTypeDataOnDemand WorkItemDataOnDemand.workItemTypeDataOnDemand;
    
    @Autowired
    WorkItemRepository WorkItemDataOnDemand.workItemRepository;
    
}
