// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.WorkItemDataOnDemand;
import org.hcmus.tis.model.WorkItemIntegrationTest;
import org.hcmus.tis.repository.WorkItemRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkItemIntegrationTest: @Transactional;
    
    @Autowired
    private WorkItemDataOnDemand WorkItemIntegrationTest.dod;
    
    @Autowired
    WorkItemRepository WorkItemIntegrationTest.workItemRepository;
    
    @Test
    public void WorkItemIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", dod.getRandomWorkItem());
        long count = workItemRepository.count();
        Assert.assertTrue("Counter for 'WorkItem' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void WorkItemIntegrationTest.testFind() {
        WorkItem obj = dod.getRandomWorkItem();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to provide an identifier", id);
        obj = workItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'WorkItem' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'WorkItem' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void WorkItemIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", dod.getRandomWorkItem());
        long count = workItemRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'WorkItem', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<WorkItem> result = workItemRepository.findAll();
        Assert.assertNotNull("Find all method for 'WorkItem' illegally returned null", result);
        Assert.assertTrue("Find all method for 'WorkItem' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void WorkItemIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", dod.getRandomWorkItem());
        long count = workItemRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<WorkItem> result = workItemRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'WorkItem' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'WorkItem' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void WorkItemIntegrationTest.testFlush() {
        WorkItem obj = dod.getRandomWorkItem();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to provide an identifier", id);
        obj = workItemRepository.findOne(id);
        Assert.assertNotNull("Find method for 'WorkItem' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyWorkItem(obj);
        Integer currentVersion = obj.getVersion();
        workItemRepository.flush();
        Assert.assertTrue("Version for 'WorkItem' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkItemIntegrationTest.testSaveUpdate() {
        WorkItem obj = dod.getRandomWorkItem();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to provide an identifier", id);
        obj = workItemRepository.findOne(id);
        boolean modified =  dod.modifyWorkItem(obj);
        Integer currentVersion = obj.getVersion();
        WorkItem merged = workItemRepository.save(obj);
        workItemRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'WorkItem' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void WorkItemIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", dod.getRandomWorkItem());
        WorkItem obj = dod.getNewTransientWorkItem(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'WorkItem' identifier to be null", obj.getId());
        workItemRepository.save(obj);
        workItemRepository.flush();
        Assert.assertNotNull("Expected 'WorkItem' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void WorkItemIntegrationTest.testDelete() {
        WorkItem obj = dod.getRandomWorkItem();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'WorkItem' failed to provide an identifier", id);
        obj = workItemRepository.findOne(id);
        workItemRepository.delete(obj);
        workItemRepository.flush();
        Assert.assertNull("Failed to remove 'WorkItem' with identifier '" + id + "'", workItemRepository.findOne(id));
    }
    
}
