package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Calendar generated by hbm2java
 */
public class Calendar  implements java.io.Serializable {


     private Integer calendarId;
     private Set projects = new HashSet(0);
     private Set events = new HashSet(0);
     private Set accounts = new HashSet(0);

    public Calendar() {
    }

    public Calendar(Set projects, Set events, Set accounts) {
       this.projects = projects;
       this.events = events;
       this.accounts = accounts;
    }
   
    public Integer getCalendarId() {
        return this.calendarId;
    }
    
    public void setCalendarId(Integer calendarId) {
        this.calendarId = calendarId;
    }
    public Set getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set projects) {
        this.projects = projects;
    }
    public Set getEvents() {
        return this.events;
    }
    
    public void setEvents(Set events) {
        this.events = events;
    }
    public Set getAccounts() {
        return this.accounts;
    }
    
    public void setAccounts(Set accounts) {
        this.accounts = accounts;
    }




}


