package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Dependencytype generated by hbm2java
 */
public class Dependencytype  implements java.io.Serializable {


     private Integer dependencyTypeId;
     private Workitemtype workitemtypeByWorkItemTypeId1;
     private Workitemtype workitemtypeByWorkItemTypeId2;
     private Process process;
     private String name;
     private Set dependencies = new HashSet(0);

    public Dependencytype() {
    }

	
    public Dependencytype(Workitemtype workitemtypeByWorkItemTypeId1, Workitemtype workitemtypeByWorkItemTypeId2, Process process, String name) {
        this.workitemtypeByWorkItemTypeId1 = workitemtypeByWorkItemTypeId1;
        this.workitemtypeByWorkItemTypeId2 = workitemtypeByWorkItemTypeId2;
        this.process = process;
        this.name = name;
    }
    public Dependencytype(Workitemtype workitemtypeByWorkItemTypeId1, Workitemtype workitemtypeByWorkItemTypeId2, Process process, String name, Set dependencies) {
       this.workitemtypeByWorkItemTypeId1 = workitemtypeByWorkItemTypeId1;
       this.workitemtypeByWorkItemTypeId2 = workitemtypeByWorkItemTypeId2;
       this.process = process;
       this.name = name;
       this.dependencies = dependencies;
    }
   
    public Integer getDependencyTypeId() {
        return this.dependencyTypeId;
    }
    
    public void setDependencyTypeId(Integer dependencyTypeId) {
        this.dependencyTypeId = dependencyTypeId;
    }
    public Workitemtype getWorkitemtypeByWorkItemTypeId1() {
        return this.workitemtypeByWorkItemTypeId1;
    }
    
    public void setWorkitemtypeByWorkItemTypeId1(Workitemtype workitemtypeByWorkItemTypeId1) {
        this.workitemtypeByWorkItemTypeId1 = workitemtypeByWorkItemTypeId1;
    }
    public Workitemtype getWorkitemtypeByWorkItemTypeId2() {
        return this.workitemtypeByWorkItemTypeId2;
    }
    
    public void setWorkitemtypeByWorkItemTypeId2(Workitemtype workitemtypeByWorkItemTypeId2) {
        this.workitemtypeByWorkItemTypeId2 = workitemtypeByWorkItemTypeId2;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getDependencies() {
        return this.dependencies;
    }
    
    public void setDependencies(Set dependencies) {
        this.dependencies = dependencies;
    }




}


