package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1



/**
 * Iteration generated by hbm2java
 */
public class Iteration  implements java.io.Serializable {


     private int iterationId;
     private Workitemcontainer workitemcontainer;

    public Iteration() {
    }

    public Iteration(Workitemcontainer workitemcontainer) {
       this.workitemcontainer = workitemcontainer;
    }
   
    public int getIterationId() {
        return this.iterationId;
    }
    
    public void setIterationId(int iterationId) {
        this.iterationId = iterationId;
    }
    public Workitemcontainer getWorkitemcontainer() {
        return this.workitemcontainer;
    }
    
    public void setWorkitemcontainer(Workitemcontainer workitemcontainer) {
        this.workitemcontainer = workitemcontainer;
    }




}


