package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project  implements java.io.Serializable {


     private int projectId;
     private Calendar calendar;
     private Projectclass projectclass;
     private Workitemcontainer workitemcontainer;
     private Process process;
     private String descriptions;
     private Set projectaccountmappings = new HashSet(0);
     private Set wikipages = new HashSet(0);

    public Project() {
    }

	
    public Project(Calendar calendar, Projectclass projectclass, Workitemcontainer workitemcontainer, Process process) {
        this.calendar = calendar;
        this.projectclass = projectclass;
        this.workitemcontainer = workitemcontainer;
        this.process = process;
    }
    public Project(Calendar calendar, Projectclass projectclass, Workitemcontainer workitemcontainer, Process process, String descriptions, Set projectaccountmappings, Set wikipages) {
       this.calendar = calendar;
       this.projectclass = projectclass;
       this.workitemcontainer = workitemcontainer;
       this.process = process;
       this.descriptions = descriptions;
       this.projectaccountmappings = projectaccountmappings;
       this.wikipages = wikipages;
    }
   
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }
    public Calendar getCalendar() {
        return this.calendar;
    }
    
    public void setCalendar(Calendar calendar) {
        this.calendar = calendar;
    }
    public Projectclass getProjectclass() {
        return this.projectclass;
    }
    
    public void setProjectclass(Projectclass projectclass) {
        this.projectclass = projectclass;
    }
    public Workitemcontainer getWorkitemcontainer() {
        return this.workitemcontainer;
    }
    
    public void setWorkitemcontainer(Workitemcontainer workitemcontainer) {
        this.workitemcontainer = workitemcontainer;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public Set getProjectaccountmappings() {
        return this.projectaccountmappings;
    }
    
    public void setProjectaccountmappings(Set projectaccountmappings) {
        this.projectaccountmappings = projectaccountmappings;
    }
    public Set getWikipages() {
        return this.wikipages;
    }
    
    public void setWikipages(Set wikipages) {
        this.wikipages = wikipages;
    }




}


