package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer statusId;
     private Workitemtype workitemtype;
     private String name;
     private Set workitems = new HashSet(0);

    public Status() {
    }

	
    public Status(Workitemtype workitemtype, String name) {
        this.workitemtype = workitemtype;
        this.name = name;
    }
    public Status(Workitemtype workitemtype, String name, Set workitems) {
       this.workitemtype = workitemtype;
       this.name = name;
       this.workitems = workitems;
    }
   
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public Workitemtype getWorkitemtype() {
        return this.workitemtype;
    }
    
    public void setWorkitemtype(Workitemtype workitemtype) {
        this.workitemtype = workitemtype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getWorkitems() {
        return this.workitems;
    }
    
    public void setWorkitems(Set workitems) {
        this.workitems = workitems;
    }




}


