package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Workitemtype generated by hbm2java
 */
public class Workitemtype  implements java.io.Serializable {


     private Integer workItemTypeId;
     private Process process;
     private String name;
     private String additionalFieldsDefine;
     private Set statuses = new HashSet(0);
     private Set workitems = new HashSet(0);
     private Set dependencytypesForWorkItemTypeId1 = new HashSet(0);
     private Set dependencytypesForWorkItemTypeId2 = new HashSet(0);

    public Workitemtype() {
    }

	
    public Workitemtype(Process process, String name, String additionalFieldsDefine) {
        this.process = process;
        this.name = name;
        this.additionalFieldsDefine = additionalFieldsDefine;
    }
    public Workitemtype(Process process, String name, String additionalFieldsDefine, Set statuses, Set workitems, Set dependencytypesForWorkItemTypeId1, Set dependencytypesForWorkItemTypeId2) {
       this.process = process;
       this.name = name;
       this.additionalFieldsDefine = additionalFieldsDefine;
       this.statuses = statuses;
       this.workitems = workitems;
       this.dependencytypesForWorkItemTypeId1 = dependencytypesForWorkItemTypeId1;
       this.dependencytypesForWorkItemTypeId2 = dependencytypesForWorkItemTypeId2;
    }
   
    public Integer getWorkItemTypeId() {
        return this.workItemTypeId;
    }
    
    public void setWorkItemTypeId(Integer workItemTypeId) {
        this.workItemTypeId = workItemTypeId;
    }
    public Process getProcess() {
        return this.process;
    }
    
    public void setProcess(Process process) {
        this.process = process;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAdditionalFieldsDefine() {
        return this.additionalFieldsDefine;
    }
    
    public void setAdditionalFieldsDefine(String additionalFieldsDefine) {
        this.additionalFieldsDefine = additionalFieldsDefine;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
    public Set getWorkitems() {
        return this.workitems;
    }
    
    public void setWorkitems(Set workitems) {
        this.workitems = workitems;
    }
    public Set getDependencytypesForWorkItemTypeId1() {
        return this.dependencytypesForWorkItemTypeId1;
    }
    
    public void setDependencytypesForWorkItemTypeId1(Set dependencytypesForWorkItemTypeId1) {
        this.dependencytypesForWorkItemTypeId1 = dependencytypesForWorkItemTypeId1;
    }
    public Set getDependencytypesForWorkItemTypeId2() {
        return this.dependencytypesForWorkItemTypeId2;
    }
    
    public void setDependencytypesForWorkItemTypeId2(Set dependencytypesForWorkItemTypeId2) {
        this.dependencytypesForWorkItemTypeId2 = dependencytypesForWorkItemTypeId2;
    }




}


