package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Workitemcontainer generated by hbm2java
 */
public class Workitemcontainer  implements java.io.Serializable {


     private Integer workItemContainerId;
     private Workitemcontainer workitemcontainer;
     private String name;
     private Set workitemcontainers = new HashSet(0);
     private Project project;
     private Set queries = new HashSet(0);
     private Set workitems = new HashSet(0);
     private Iteration iteration;

    public Workitemcontainer() {
    }

	
    public Workitemcontainer(Workitemcontainer workitemcontainer, String name) {
        this.workitemcontainer = workitemcontainer;
        this.name = name;
    }
    public Workitemcontainer(Workitemcontainer workitemcontainer, String name, Set workitemcontainers, Project project, Set queries, Set workitems, Iteration iteration) {
       this.workitemcontainer = workitemcontainer;
       this.name = name;
       this.workitemcontainers = workitemcontainers;
       this.project = project;
       this.queries = queries;
       this.workitems = workitems;
       this.iteration = iteration;
    }
   
    public Integer getWorkItemContainerId() {
        return this.workItemContainerId;
    }
    
    public void setWorkItemContainerId(Integer workItemContainerId) {
        this.workItemContainerId = workItemContainerId;
    }
    public Workitemcontainer getWorkitemcontainer() {
        return this.workitemcontainer;
    }
    
    public void setWorkitemcontainer(Workitemcontainer workitemcontainer) {
        this.workitemcontainer = workitemcontainer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getWorkitemcontainers() {
        return this.workitemcontainers;
    }
    
    public void setWorkitemcontainers(Set workitemcontainers) {
        this.workitemcontainers = workitemcontainers;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public Set getQueries() {
        return this.queries;
    }
    
    public void setQueries(Set queries) {
        this.queries = queries;
    }
    public Set getWorkitems() {
        return this.workitems;
    }
    
    public void setWorkitems(Set workitems) {
        this.workitems = workitems;
    }
    public Iteration getIteration() {
        return this.iteration;
    }
    
    public void setIteration(Iteration iteration) {
        this.iteration = iteration;
    }




}


