package pojo;
// Generated Mar 10, 2012 10:58:54 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workitem generated by hbm2java
 */
public class Workitem  implements java.io.Serializable {


     private Integer workItemId;
     private Status status;
     private Account accountByAsigneeId;
     private Workitemtype workitemtype;
     private Account accountByAuthorId;
     private Workitemcontainer workitemcontainer;
     private String title;
     private String description;
     private Date dateCreated;
     private Integer priority;
     private Integer changeSet;
     private String additionalFields;
     private Date dueDate;
     private Date lastModifyDate;
     private Set dependenciesForWorkItemId1 = new HashSet(0);
     private Set dependenciesForWorkItemId2 = new HashSet(0);
     private Set workitemcomments = new HashSet(0);

    public Workitem() {
    }

	
    public Workitem(Status status, Account accountByAsigneeId, Workitemtype workitemtype, Account accountByAuthorId, Workitemcontainer workitemcontainer, String title, Date dateCreated, Date lastModifyDate) {
        this.status = status;
        this.accountByAsigneeId = accountByAsigneeId;
        this.workitemtype = workitemtype;
        this.accountByAuthorId = accountByAuthorId;
        this.workitemcontainer = workitemcontainer;
        this.title = title;
        this.dateCreated = dateCreated;
        this.lastModifyDate = lastModifyDate;
    }
    public Workitem(Status status, Account accountByAsigneeId, Workitemtype workitemtype, Account accountByAuthorId, Workitemcontainer workitemcontainer, String title, String description, Date dateCreated, Integer priority, Integer changeSet, String additionalFields, Date dueDate, Date lastModifyDate, Set dependenciesForWorkItemId1, Set dependenciesForWorkItemId2, Set workitemcomments) {
       this.status = status;
       this.accountByAsigneeId = accountByAsigneeId;
       this.workitemtype = workitemtype;
       this.accountByAuthorId = accountByAuthorId;
       this.workitemcontainer = workitemcontainer;
       this.title = title;
       this.description = description;
       this.dateCreated = dateCreated;
       this.priority = priority;
       this.changeSet = changeSet;
       this.additionalFields = additionalFields;
       this.dueDate = dueDate;
       this.lastModifyDate = lastModifyDate;
       this.dependenciesForWorkItemId1 = dependenciesForWorkItemId1;
       this.dependenciesForWorkItemId2 = dependenciesForWorkItemId2;
       this.workitemcomments = workitemcomments;
    }
   
    public Integer getWorkItemId() {
        return this.workItemId;
    }
    
    public void setWorkItemId(Integer workItemId) {
        this.workItemId = workItemId;
    }
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }
    public Account getAccountByAsigneeId() {
        return this.accountByAsigneeId;
    }
    
    public void setAccountByAsigneeId(Account accountByAsigneeId) {
        this.accountByAsigneeId = accountByAsigneeId;
    }
    public Workitemtype getWorkitemtype() {
        return this.workitemtype;
    }
    
    public void setWorkitemtype(Workitemtype workitemtype) {
        this.workitemtype = workitemtype;
    }
    public Account getAccountByAuthorId() {
        return this.accountByAuthorId;
    }
    
    public void setAccountByAuthorId(Account accountByAuthorId) {
        this.accountByAuthorId = accountByAuthorId;
    }
    public Workitemcontainer getWorkitemcontainer() {
        return this.workitemcontainer;
    }
    
    public void setWorkitemcontainer(Workitemcontainer workitemcontainer) {
        this.workitemcontainer = workitemcontainer;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    public Integer getChangeSet() {
        return this.changeSet;
    }
    
    public void setChangeSet(Integer changeSet) {
        this.changeSet = changeSet;
    }
    public String getAdditionalFields() {
        return this.additionalFields;
    }
    
    public void setAdditionalFields(String additionalFields) {
        this.additionalFields = additionalFields;
    }
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }
    public Date getLastModifyDate() {
        return this.lastModifyDate;
    }
    
    public void setLastModifyDate(Date lastModifyDate) {
        this.lastModifyDate = lastModifyDate;
    }
    public Set getDependenciesForWorkItemId1() {
        return this.dependenciesForWorkItemId1;
    }
    
    public void setDependenciesForWorkItemId1(Set dependenciesForWorkItemId1) {
        this.dependenciesForWorkItemId1 = dependenciesForWorkItemId1;
    }
    public Set getDependenciesForWorkItemId2() {
        return this.dependenciesForWorkItemId2;
    }
    
    public void setDependenciesForWorkItemId2(Set dependenciesForWorkItemId2) {
        this.dependenciesForWorkItemId2 = dependenciesForWorkItemId2;
    }
    public Set getWorkitemcomments() {
        return this.workitemcomments;
    }
    
    public void setWorkitemcomments(Set workitemcomments) {
        this.workitemcomments = workitemcomments;
    }




}


