// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Iteration;
import org.hcmus.tis.model.IterationDataOnDemand;
import org.hcmus.tis.model.WorkItemContainer;
import org.springframework.stereotype.Component;

privileged aspect IterationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IterationDataOnDemand: @Component;
    
    private Random IterationDataOnDemand.rnd = new SecureRandom();
    
    private List<Iteration> IterationDataOnDemand.data;
    
}
