// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Account;
import org.hcmus.tis.model.AccountDataOnDemand;
import org.hcmus.tis.model.MemberInformation;
import org.hcmus.tis.model.MemberInformationDataOnDemand;
import org.hcmus.tis.model.MemberRole;
import org.hcmus.tis.model.MemberRoleDataOnDemand;
import org.hcmus.tis.model.Project;
import org.hcmus.tis.model.ProjectDataOnDemand;
import org.hcmus.tis.repository.MemberInformationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MemberInformationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MemberInformationDataOnDemand: @Component;
    
    private Random MemberInformationDataOnDemand.rnd = new SecureRandom();
    
    private List<MemberInformation> MemberInformationDataOnDemand.data;
    
    @Autowired
    private AccountDataOnDemand MemberInformationDataOnDemand.accountDataOnDemand;
    
    @Autowired
    private MemberRoleDataOnDemand MemberInformationDataOnDemand.memberRoleDataOnDemand;
    
    @Autowired
    private ProjectDataOnDemand MemberInformationDataOnDemand.projectDataOnDemand;
    
    @Autowired
    MemberInformationRepository MemberInformationDataOnDemand.memberInformationRepository;
    
}
