// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Priority;
import org.hcmus.tis.model.PriorityDataOnDemand;
import org.hcmus.tis.repository.PriorityRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect PriorityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PriorityDataOnDemand: @Component;
    
    private Random PriorityDataOnDemand.rnd = new SecureRandom();
    
    private List<Priority> PriorityDataOnDemand.data;
    
    @Autowired
    PriorityRepository PriorityDataOnDemand.priorityRepository;
    
    public Priority PriorityDataOnDemand.getNewTransientPriority(int index) {
        Priority obj = new Priority();
        setName(obj, index);
        return obj;
    }
    
    public void PriorityDataOnDemand.setName(Priority obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public Priority PriorityDataOnDemand.getSpecificPriority(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Priority obj = data.get(index);
        Long id = obj.getId();
        return priorityRepository.findOne(id);
    }
    
    public Priority PriorityDataOnDemand.getRandomPriority() {
        init();
        Priority obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return priorityRepository.findOne(id);
    }
    
    public boolean PriorityDataOnDemand.modifyPriority(Priority obj) {
        return false;
    }
    
    public void PriorityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = priorityRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Priority' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Priority>();
        for (int i = 0; i < 10; i++) {
            Priority obj = getNewTransientPriority(i);
            try {
                priorityRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            priorityRepository.flush();
            data.add(obj);
        }
    }
    
}
