// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.Project;
import org.hcmus.tis.model.ProjectDataOnDemand;
import org.hcmus.tis.model.ProjectProcess;
import org.hcmus.tis.model.ProjectProcessDataOnDemand;
import org.hcmus.tis.model.ProjectStatus;
import org.hcmus.tis.model.StudyClass;
import org.hcmus.tis.model.StudyClassDataOnDemand;
import org.hcmus.tis.model.WorkItemContainer;
import org.hcmus.tis.repository.EventRepository;
import org.hcmus.tis.repository.ProjectRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ProjectDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProjectDataOnDemand: @Component;
    
    private Random ProjectDataOnDemand.rnd = new SecureRandom();
    
    private List<Project> ProjectDataOnDemand.data;
    
    @Autowired
    private ProjectProcessDataOnDemand ProjectDataOnDemand.projectProcessDataOnDemand;
    
    @Autowired
    private StudyClassDataOnDemand ProjectDataOnDemand.studyClassDataOnDemand;
    
    @Autowired
    ProjectRepository ProjectDataOnDemand.projectRepository;
    
    public Project ProjectDataOnDemand.getNewTransientProject(int index) {
        Project obj = new Project();
        setDescription(obj, index);
        setEventRepository(obj, index);
        setName(obj, index);
        setParentContainer(obj, index);
        setProjectProcess(obj, index);
        setStatus(obj, index);
        setStudyClass(obj, index);
        return obj;
    }
    
    public void ProjectDataOnDemand.setDescription(Project obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void ProjectDataOnDemand.setEventRepository(Project obj, int index) {
        EventRepository eventRepository = null;
        obj.setEventRepository(eventRepository);
    }
    
    public void ProjectDataOnDemand.setName(Project obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void ProjectDataOnDemand.setParentContainer(Project obj, int index) {
        WorkItemContainer parentContainer = null;
        obj.setParentContainer(parentContainer);
    }
    
    public void ProjectDataOnDemand.setProjectProcess(Project obj, int index) {
        ProjectProcess projectProcess = projectProcessDataOnDemand.getRandomProjectProcess();
        obj.setProjectProcess(projectProcess);
    }
    
    public void ProjectDataOnDemand.setStatus(Project obj, int index) {
        ProjectStatus status = ProjectStatus.class.getEnumConstants()[0];
        obj.setStatus(status);
    }
    
    public void ProjectDataOnDemand.setStudyClass(Project obj, int index) {
        StudyClass studyClass = studyClassDataOnDemand.getRandomStudyClass();
        obj.setStudyClass(studyClass);
    }
    
    public Project ProjectDataOnDemand.getSpecificProject(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Project obj = data.get(index);
        Long id = obj.getId();
        return projectRepository.findOne(id);
    }
    
    public Project ProjectDataOnDemand.getRandomProject() {
        init();
        Project obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return projectRepository.findOne(id);
    }
    
    public boolean ProjectDataOnDemand.modifyProject(Project obj) {
        return false;
    }
    
    public void ProjectDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = projectRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Project' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Project>();
        for (int i = 0; i < 10; i++) {
            Project obj = getNewTransientProject(i);
            try {
                projectRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            projectRepository.flush();
            data.add(obj);
        }
    }
    
}
