// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.StudyClass;
import org.hcmus.tis.model.StudyClassDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect StudyClassDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StudyClassDataOnDemand: @Component;
    
    private Random StudyClassDataOnDemand.rnd = new SecureRandom();
    
    private List<StudyClass> StudyClassDataOnDemand.data;
    
    public StudyClass StudyClassDataOnDemand.getNewTransientStudyClass(int index) {
        StudyClass obj = new StudyClass();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void StudyClassDataOnDemand.setDescription(StudyClass obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void StudyClassDataOnDemand.setName(StudyClass obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public StudyClass StudyClassDataOnDemand.getSpecificStudyClass(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StudyClass obj = data.get(index);
        Long id = obj.getId();
        return StudyClass.findStudyClass(id);
    }
    
    public StudyClass StudyClassDataOnDemand.getRandomStudyClass() {
        init();
        StudyClass obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return StudyClass.findStudyClass(id);
    }
    
    public boolean StudyClassDataOnDemand.modifyStudyClass(StudyClass obj) {
        return false;
    }
    
    public void StudyClassDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StudyClass.findStudyClassEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StudyClass' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StudyClass>();
        for (int i = 0; i < 10; i++) {
            StudyClass obj = getNewTransientStudyClass(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
