// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.util.List;
import org.hcmus.tis.model.WorkItemDataOnDemand;
import org.hcmus.tis.model.WorkItemIntegrationTest;
import org.hcmus.tis.repository.WorkItemRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WorkItemIntegrationTest_Roo_IntegrationTest {
    
    declare @type: WorkItemIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: WorkItemIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: WorkItemIntegrationTest: @Transactional;
    
    @Autowired
    private WorkItemDataOnDemand WorkItemIntegrationTest.dod;
    
    @Autowired
    WorkItemRepository WorkItemIntegrationTest.workItemRepository;
    
}
