// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.ProjectProcess;
import org.hcmus.tis.model.WorkItemType;
import org.hcmus.tis.model.WorkItemTypeDataOnDemand;
import org.springframework.stereotype.Component;

privileged aspect WorkItemTypeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkItemTypeDataOnDemand: @Component;
    
    private Random WorkItemTypeDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkItemType> WorkItemTypeDataOnDemand.data;
    
    public WorkItemType WorkItemTypeDataOnDemand.getNewTransientWorkItemType(int index) {
        WorkItemType obj = new WorkItemType();
        setAdditionalFieldsDefine(obj, index);
        setName(obj, index);
        setProjectProcess(obj, index);
        return obj;
    }
    
    public void WorkItemTypeDataOnDemand.setAdditionalFieldsDefine(WorkItemType obj, int index) {
        String additionalFieldsDefine = "additionalFieldsDefine_" + index;
        obj.setAdditionalFieldsDefine(additionalFieldsDefine);
    }
    
    public void WorkItemTypeDataOnDemand.setName(WorkItemType obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void WorkItemTypeDataOnDemand.setProjectProcess(WorkItemType obj, int index) {
        ProjectProcess projectProcess = null;
        obj.setProjectProcess(projectProcess);
    }
    
    public WorkItemType WorkItemTypeDataOnDemand.getSpecificWorkItemType(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WorkItemType obj = data.get(index);
        Long id = obj.getId();
        return WorkItemType.findWorkItemType(id);
    }
    
    public WorkItemType WorkItemTypeDataOnDemand.getRandomWorkItemType() {
        init();
        WorkItemType obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return WorkItemType.findWorkItemType(id);
    }
    
    public boolean WorkItemTypeDataOnDemand.modifyWorkItemType(WorkItemType obj) {
        return false;
    }
    
    public void WorkItemTypeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = WorkItemType.findWorkItemTypeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WorkItemType' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WorkItemType>();
        for (int i = 0; i < 10; i++) {
            WorkItemType obj = getNewTransientWorkItemType(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
