// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.hcmus.tis.model.WorkItemStatus;
import org.hcmus.tis.model.WorkItemStatusDataOnDemand;
import org.hcmus.tis.repository.WorkItemStatusRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect WorkItemStatusDataOnDemand_Roo_DataOnDemand {
    
    declare @type: WorkItemStatusDataOnDemand: @Component;
    
    private Random WorkItemStatusDataOnDemand.rnd = new SecureRandom();
    
    private List<WorkItemStatus> WorkItemStatusDataOnDemand.data;
    
    @Autowired
    WorkItemStatusRepository WorkItemStatusDataOnDemand.workItemStatusRepository;
    
    public WorkItemStatus WorkItemStatusDataOnDemand.getNewTransientWorkItemStatus(int index) {
        WorkItemStatus obj = new WorkItemStatus();
        setClosed(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void WorkItemStatusDataOnDemand.setClosed(WorkItemStatus obj, int index) {
        Boolean closed = true;
        obj.setClosed(closed);
    }
    
    public void WorkItemStatusDataOnDemand.setName(WorkItemStatus obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public WorkItemStatus WorkItemStatusDataOnDemand.getSpecificWorkItemStatus(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        WorkItemStatus obj = data.get(index);
        Long id = obj.getId();
        return workItemStatusRepository.findOne(id);
    }
    
    public WorkItemStatus WorkItemStatusDataOnDemand.getRandomWorkItemStatus() {
        init();
        WorkItemStatus obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return workItemStatusRepository.findOne(id);
    }
    
    public boolean WorkItemStatusDataOnDemand.modifyWorkItemStatus(WorkItemStatus obj) {
        return false;
    }
    
    public void WorkItemStatusDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = workItemStatusRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'WorkItemStatus' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<WorkItemStatus>();
        for (int i = 0; i < 10; i++) {
            WorkItemStatus obj = getNewTransientWorkItemStatus(i);
            try {
                workItemStatusRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            workItemStatusRepository.flush();
            data.add(obj);
        }
    }
    
}
