// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import org.hcmus.tis.model.Priority;

privileged aspect Priority_Roo_JavaBean {
    
    public String Priority.getName() {
        return this.name;
    }
    
    public void Priority.setName(String name) {
        this.name = name;
    }
    
}
