// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.hcmus.tis.model;

import javax.persistence.Entity;
import org.hcmus.tis.model.WorkItemCreation;

privileged aspect WorkItemCreation_Roo_Jpa_Entity {
    
    declare @type: WorkItemCreation: @Entity;
    
}
