//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.23 at 09:37:43 PM ICT 
//


package org.hcmus.tis.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xProjectProcess complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xProjectProcess">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xWorkItems" type="{http://www.w3schools.com}xWorkItems"/>
 *         &lt;element name="xDescription" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="identity" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xProjectProcess", propOrder = {
    "xWorkItems",
    "xDescription"
})
public class XProjectProcess {

    @XmlElement(required = true)
    protected XWorkItems xWorkItems;
    @XmlElement(required = true)
    protected Object xDescription;
    @XmlAttribute(name = "identity", required = true)
    protected String identity;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the xWorkItems property.
     * 
     * @return
     *     possible object is
     *     {@link XWorkItems }
     *     
     */
    public XWorkItems getXWorkItems() {
        return xWorkItems;
    }

    /**
     * Sets the value of the xWorkItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link XWorkItems }
     *     
     */
    public void setXWorkItems(XWorkItems value) {
        this.xWorkItems = value;
    }

    /**
     * Gets the value of the xDescription property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getXDescription() {
        return xDescription;
    }

    /**
     * Sets the value of the xDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setXDescription(Object value) {
        this.xDescription = value;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentity(String value) {
        this.identity = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
