//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.12 at 02:41:24 PM ICT 
//


package org.hcmus.tis.model.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for xBuildInType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="xBuildInType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="number"/>
 *     &lt;enumeration value="digits"/>
 *     &lt;enumeration value="date"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "xBuildInType")
@XmlEnum
public enum XBuildInType {

    @XmlEnumValue("string")
    STRING("string"),
    @XmlEnumValue("number")
    NUMBER("number"),
    @XmlEnumValue("digits")
    DIGITS("digits"),
    @XmlEnumValue("date")
    DATE("date");
    private final String value;

    XBuildInType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static XBuildInType fromValue(String v) {
        for (XBuildInType c: XBuildInType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
